name: notify
description: Notify
inputs:
  token:
    description: GitHub token to access repositories releases.
    required: true
  repository:
    description: The org/repo containing the release. Defaults to the current repo.
    required: false
  title:
    description: The title of the issue.
    required: true
  contentFilepath:
    description: The path to the file containing the content of the issue.
    required: true

outputs:
  issueNumber:
    description: The issue number.

runs:
  using: node16
  main: ./index.js
